cloud:
  aws:
    credentials:
      access-key: AKIAW6QYM5DKEGC54LM6
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: file-upload-s3test

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

