cloud:
  aws:
    credentials:
      access-key: AKIAW6QYM5DKLKVD45FX
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: file-upload-s3test

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

